# nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/3d_hydrogenlike.py H 1 >> /clusterfs/students/achmadjae/RA/02_deep3D/script/data_log/H_.log  
nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/3d_hydrogenlike.py He 2 >> /clusterfs/students/achmadjae/RA/02_deep3D/script/data_log/He_.log &
nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/3d_hydrogenlike.py Li 3 >> /clusterfs/students/achmadjae/RA/02_deep3D/script/data_log/Li_.log &  
nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/3d_hydrogenlike.py Be 4 >> /clusterfs/students/achmadjae/RA/02_deep3D/script/data_log/Be_.log &  
# nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/main.py H train >> /clusterfs/students/achmadjae/RA/02_deep3D/script/train_log/H_.log  
# nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/main.py He train >> /clusterfs/students/achmadjae/RA/02_deep3D/script/train_log/He_.log  
# nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/main.py Li train >> /clusterfs/students/achmadjae/RA/02_deep3D/script/train_log/Li_.log  
# nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/main.py Be train >> /clusterfs/students/achmadjae/RA/02_deep3D/script/train_log/Be_.log  
# nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/main.py H test >> /clusterfs/students/achmadjae/RA/02_deep3D/script/test_log/H_.log  
# nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/main.py He test >> /clusterfs/students/achmadjae/RA/02_deep3D/script/test_log/He_.log  
# nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/main.py Li test >> /clusterfs/students/achmadjae/RA/02_deep3D/script/test_log/Li_.log  
# nohup python /clusterfs/students/achmadjae/RA/02_deep3D/script/main.py Be test >> /clusterfs/students/achmadjae/RA/02_deep3D/script/test_log/Be_.log
